### ISSUE TITLE
Thermostat widget sends wrong command. Z-Way 2.1.1

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/ExpertUI#146]
If you select a temperature, the command is send:
http://192.168.0.62:8083/ZWaveAPI/Run/devices[30].instances[0].commandClasses[64].Set(1,30)

Should:
http://192.168.0.62:8083/ZWaveAPI/Run/devices[30].instances[0].commandClasses[67].Set(1,30)

Diff: [64] - [67]
<img width="1273" alt="2015-09-23 17 13 29" src="https://cloud.githubusercontent.com/assets/2894860/10047662/d3d207a6-6217-11e5-8ced-dbcf721ff67c.png">

Command Class 64 used to change mode. 
devices[30].instances[0].commandClasses[64].Set(1)
1 - Heat Mode

Command Class 67 used to change temperature for mode. devices[30].instances[0].commandClasses[67].Set(1,30)
1- Heat Mode
30 - Temperature

**Comment by vades** [comment]
What is the name of the Thermostat that you use in your screenshot?

**Comment by aivs** [comment]
I tested with iTemp, Z-Wave.Me FT, Remotec ZXT-120,

**Comment by vades** [comment]
Fixed:
Change temperature; ZWave.zway/Run/devices[19].instances[0].commandClasses[67].Set(1,21)
Change mode; /ZWave.zway/Run/devices[19].instances[0].commandClasses[64].Set(1)

**Comment by aivs** [comment]
Now Mode and Temperature can be set. But UI has a bug. In mode "Off" temperature slider not shown, then select mode "Heat" and temperature slider NOT APPEAR! Need page reload! 
After page reload temperature slider appears, then select mode "Off" and temperature slider NOT DISAPPEAR! Need page reload!
<img width="1280" alt="2016-06-16 14 40 03" src="https://cloud.githubusercontent.com/assets/2894860/16115615/db075f72-33d0-11e6-89d1-6d3680931d20.png">
<img width="1280" alt="2016-06-16 14 40 15" src="https://cloud.githubusercontent.com/assets/2894860/16115619/e53e03c4-33d0-11e6-93cd-5bacb0688c59.png">

**Comment by aivs** [comment]
BUG with disappeared temperature slider still have in 2.2.4
<img width="1280" alt="2016-10-27 18 40 39" src="https://cloud.githubusercontent.com/assets/2894860/19774314/50a871aa-9c75-11e6-9e52-0616d4b19aa2.png">

**Comment by pz1** [comment]
FWIW: For StellaZ this page (but also the temperature setting in SmartHome) has become completely useless since a couple of versions back.

**Comment by vades** [comment]
BUG with disappeared temperature slider  is fixed but  will be in the next release.

**Comment by aivs** [comment]
Not Fixed. Temperature slider disappeared
<img width="1280" alt="2017-03-09 19 07 55" src="https://cloud.githubusercontent.com/assets/2894860/23758740/ba43d17e-04fb-11e7-8b70-cf0cb726694d.png">

**Comment by vades** [comment]
Is this really bug or I missed something? The task fo thermostat with MODE was:
1. When MODE is OFF: SHOW buttins and slider
![mode-off](https://cloud.githubusercontent.com/assets/1451741/23786057/170c5844-056b-11e7-98c5-7fd9c7821952.png)

2. When mod is selected: HIDE buttons and slider
![mode-on](https://cloud.githubusercontent.com/assets/1451741/23786063/1c5433a8-056b-11e7-8d4a-e80d6fad5924.png)

I have no information that  It should be different

**Comment by aivs** [comment]
Ohhh...
When thermostat is Off, no need to set temperature.
When thermostat working in one of the modes (Heat, Cool, Energy Save, etc), need to set temperature.

So, 
Off mode - no buttons, no slider.
Other modes - buttons +/-, slider.

**Comment by vades** [comment]
Thanks.It's added  into our internal  Task Manager

**Comment by vades** [comment]
Now are elements hidden if

1. Thermostat has NO Setpoint
2. Thermostat is OFF
3. Thermostad is ON (has mode) but has NO Setpoint

**Comment by aivs** [comment]
<img width="1280" alt="2017-06-29 17 35 16" src="https://user-images.githubusercontent.com/2894860/27693266-9838aa66-5cf1-11e7-801f-054cca9059a1.png">

Now you send wrong command at mode change
Need 64 instead 67.
devices[80].instances[0].commandClasses[64].Set(2)
In expert commands all ok

**Comment by aivs** [comment]
The problem is still there in version 2.3.5

**Comment by aivs** [comment]
Tested with FT, works
