### ISSUE TITLE
Restore does not work with Firefox on v2.0.0-rc25

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/ExpertUI#99]
Restore does not seem to work with Firefox (38.0.5)  on v2.0.0-rc35. This problem does not occur with Chrome and Opera [(see here)](http://forum.z-wave.me/viewtopic.php?f=3424&t=21011&p=56393#p56393)

**Comment by PoltoS** [comment]
Fixed

**Comment by pz1** [comment]
v2.1.1 I still can't restore a backup with Firefox (41.0.2): I just don't get the backup file selector menus. The button does not respond.

**Comment by PoltoS** [comment]
Fix in progress. Button was fixed, but now we are tunning the hardware (RaZ/UZB)

**Comment by ronie-z-wave** [comment]
fixed https://github.com/Z-Wave-Me/ExpertUI/commit/8601eb762ab24acafc8ce68603db2f3c614f6f7e
